Prepare for govuk-prototype-kit migration
Background

The app currently errors when starting up with the following message:

```
[...]/dxw-prototype-lib/lib/extensions/extensions.js:75
    throw new Error(`All extension paths must start with a forward slash - "${subject.packageName}" used "${subject.item}".`)
    ^

Error: All extension paths must start with a forward slash - "govuk-frontend" used "[object Object]".
    at throwIfBadFilepath (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/extensions/extensions.js:75:11)
    at getFileSystemPath (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/extensions/extensions.js:145:3)
    at getPublicUrlAndFileSystemPath (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/extensions/extensions.js:152:19)
    at Array.map (<anonymous>)
    at Object.getPublicUrlAndFileSystemPaths (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/extensions/extensions.js:162:57)
    at setupPathsFor (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/middleware/extensions/extensions.js:7:14)
    at Object.<anonymous> (/Users/ynda/code/github.com/dxw/dxw-prototype-lib/lib/middleware/extensions/extensions.js:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
```

This app has no tests, so it's likely that a Renovate upgrade PR was
incompatible with govuk-prototype-kit@12.2.0 and therefore broke things
quietly. This was only noticed when someone tried to look at the app on
Heroku

I was able to get the app running fine by adjusting some code in
lib/extensions/extensions.js and
lib/middleware/extensions/extensions.js, but the server logs showed some
missing file errors and this felt a bit hacky. These lib files were
generated when installing the app from govuk-prototype-kit@12.2.0 and
hadn't been touched since

Migrating to the latest version of govuk-prototype-kit will fix these
issues without introducing errors in the server logs. Since it's not a
regular Node dependency but rather a template installed via a script,
the migration/upgrade process requires a bit more manual intervention

---

This commit

This resets the app/views/layout.html file to its 12.2.0 default and
removes the app/view/layout.html file, which together will allow the
migration script to run without error. We haven't changed the latter;
our changes to the former will be reapplied post-migration